### ISSUE TITLE
 Upgrade to vue.js 2.0

### ISSUE THREAD

**Issue by talvbansal** [talvbansal/media-manager#10]
With the new release of Vue.js 2.0 we should create a final Vue.js 1.x branch for legacy use and then make the master branch and all future tags use Vue.js 2.0.

The biggest thing that will need work currently is the removal of the .sync feature that is being used to track state between components internally. I'd love for anyone to start looking at how we can re-write this to take advantage of Vue.js 2.0

**Comment by talvbansal** [comment]
The code for this change is now on the `vue2` branch, however I have the following issue that is stopping me merging this into the `master` branch:

When running `gulp --production` the code gets generated correctly and minified as expected, but when you include the media manager into your project and run `gulp` or `gulp --production` the following error gets generated:

```javascript
[10:03:27] Starting 'webpack'...
{ [Error: ./vendor/talvbansal/media-manager/public/js/media-manager.js
Module build failed: SyntaxError: 'with' in strict mode (10:9256)
    at Parser.pp$4.raise (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$1.parseWithStatement (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:932:27)
    at Parser.pp$1.parseStatement (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:708:32)
    at Parser.pp$1.parseBlock (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$1.parseFunction (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:1065:10)
    at Parser.pp$3.parseExprAtom (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:1810:19)
    at Parser.parseExprAtom (/home/talv/Projects/sso/node_modules/buble/dist/buble.umd.js:656:26)
    at Parser.pp$3.parseExprSubscripts (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:1692:19)
 @ ./resources/assets/js/admin.js 4:0-77]
  message: './vendor/talvbansal/media-manager/public/js/media-manager.js\nModule build failed: SyntaxError: \'with\' in strict mode (10:9256)\n    at Parser.pp$4.raise (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:2221:15)\n    at Parser.pp$1.parseWithStatement (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:932:27)\n    at Parser.pp$1.parseStatement (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:708:32)\n    at Parser.pp$1.parseBlock (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:981:25)\n    at Parser.pp$3.parseFunctionBody (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:2105:24)\n    at Parser.pp$1.parseFunction (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:1065:10)\n    at Parser.pp$3.parseExprAtom (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:1810:19)\n    at Parser.parseExprAtom (/home/talv/Projects/sso/node_modules/buble/dist/buble.umd.js:656:26)\n    at Parser.pp$3.parseExprSubscripts (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:1715:21)\n    at Parser.pp$3.parseMaybeUnary (/home/talv/Projects/sso/node_modules/acorn/dist/acorn.js:1692:19)\n @ ./resources/assets/js/admin.js 4:0-77',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }

```

However when running a normal `gulp` (not minified output) when building the media manager allows the build to success within a child project.

Does anyone have any ideas?
